plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
# Navigation
navs:
  -
    href: jump1
    label: jump1

  -
    href: /jump1
    label: jump1

  -
    href: /publications/
    label: Publications

  -
    href: /categories/
    label: Blogs

  -
    href: /wiki/
    label: Wiki

title: page 2022
theme: jekyll-theme-architect